name: treeview_challenge
description: 'A Flutter application for visualizing and managing hierarchical asset data using a tree view.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  result_dart: ^1.1.1
  http: ^1.2.2
  provider: ^6.1.2
  get: ^4.6.6




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^1.0.4
  collection: ^1.18.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: TractianIcons
      fonts:
        - asset: assets/fonts/TractianIcons.ttf

