/// Flutter icons TractianIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TractianIcons
///      fonts:
///       - asset: fonts/TractianIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TractianIcons {
  TractianIcons._();

  static const _kFontFam = 'TractianIcons';
  static const String? _kFontPkg = null;

  static const IconData bolt_outlined = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData company = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asset = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bolt_filled = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData component = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
